-- have database created in postgres before migrating table to database

DROP TABLE  quotes;

CREATE TABLE quotes (
    id SERIAL PRIMARY KEY,
    quote text
);

INSERT INTO quotes (quote) VALUES ('Colors bounced around in her head They mixed and threaded themselves together Even colors that had no business being together They were all one yet distinctly separate at the same time');
INSERT INTO quotes (quote) VALUES ('Its always good to bring a slower friend with you on a hike If you happen to come across bears the whole group doesnt have to worry Only the slowest in the group do');
INSERT INTO quotes (quote) VALUES ('Youre going to make a choice today that will have a direct impact on where you are five years from now. The truth is youll make choice like that every day of your life The problem is that on most days you wont know the choice you make will have such a huge impact on your life in the future');
INSERT INTO quotes (quote) VALUES ('Eating raw fish didnt sound like a good idea Its a delicacy in Japan didnt seem to make it any more appetizing Raw fish is raw fish delicacy or not');
INSERT INTO quotes (quote) VALUES ('Her hand was balled into a fist with her keys protruding out from between her fingers This was the weapon her father had shown her how to make when she walked alone to her car after work');
INSERT INTO quotes (quote) VALUES ('I checked in for the night at Out O The Way motel What a bad choice that was First I took a shower and a spider crawled out of the drain Next the towel rack fell down when I reached for the one small bath towel');
INSERT INTO quotes (quote) VALUES ('Im meant to be writing at this moment. What I mean is, Im meant to be writing something else at this moment. The document Im meant to be writing is, of course, open in another program on my computer and is patiently awaiting my attention.');
INSERT INTO quotes (quote) VALUES ('She has seen this scene before. It had come to her in dreams many times before. She had to pinch herself to make sure it wasnt a dream again. As her fingers squeezed against her arm, she felt the pain.');
INSERT INTO quotes (quote) VALUES ('There was nothing else to do. The deed had already been done and there was no going back. It now had been become a question of how they were going to be able to get out of this situation and escape.');
INSERT INTO quotes (quote) VALUES ('Im going to hire professional help tomorrow. I cant handle this anymore. She fell over the coffee table and now there is blood in her catheter. This is much more than I ever signed up to do.');
INSERT INTO quotes (quote) VALUES ('It had been an off-hand observation on his ability to hold a conversation and actually add pertinent information to it on practically any topic. Although he hadnt consciously strived to be able to do so, hed started to voraciously read the news when he couldnt keep up on topics his friends discussed because their conversations went above his head.');
INSERT INTO quotes (quote) VALUES ('I love the feel of wood curls flying off the lathe as I begin to shape the log in front of me. The sound of scraping changes based on the wetness of the wood, the speed at which the lathe is turning, and the type of cut I am making. The smell and feel of wet wood being turned are unique.');
INSERT INTO quotes (quote) VALUES ('Puppies are soft, cute, funny, and make a big mess. Every month or two our family fosters 6-12 week old puppies for a puppy rescue nonprofit organization. We all enjoy cuddling their furry bodies after a clean bath. Fresh puppy smell is great.');
INSERT INTO quotes (quote) VALUES ('It was cloudy outside but not really raining. There was a light sprinkle at most and there certainly wasnt a need for an umbrella. This hadnt stopped Sarah from pulling her umbrella out and opening it.');
INSERT INTO quotes (quote) VALUES ('The water rush down the wash and into the slot canyon below. Two hikers had started the day to sunny weather without a cloud in the sky, but they hadnt thought to check the weather north of the canyon.');
INSERT INTO quotes (quote) VALUES ('Indescribable oppression, which seemed to generate in some unfamiliar part of her consciousness, filled her whole being with a vague anguish. It was like a shadow, like a mist passing across her souls summer day.');
INSERT INTO quotes (quote) VALUES ('There wasnt a whole lot more that could be done. It had become a wait-and-see situation with the final results no longer in her control. That didnt stop her from trying to control the situation.');
INSERT INTO quotes (quote) VALUES ('April seriously wondered about her sleeping partner choices. She looked at her bed and what a mess it had become. How did she get to the point in her life where she had two dogs, three cats.');
INSERT INTO quotes (quote) VALUES ('It had been a rough day. Things hadnt gone as planned and that meant Hannah got yelled at by her boss. It didnt even matter that it wasnt her fault. When things went wrong at work, Hannah got the blame no matter the actual circumstances.');
INSERT INTO quotes (quote) VALUES ('Time is all relative based on age and experience. When you are a child an hour is a long time to wait but a very short time when thats all the time you are allowed on your iPad. As a teenager time goes faster the more deadlines you have and the more you procrastinate.');
INSERT INTO quotes (quote) VALUES ('Finding the red rose in the mailbox was a pleasant surprise for Sarah. She didnt have a boyfriend or know of anyone who was interested in her as anything more than a friend. There wasnt even a note attached to it.');
INSERT INTO quotes (quote) VALUES ('There was nothing to indicate Nancy was going to change the world. She looked like an average girl going to an average high school. It was the fact that everything about her seemed average that would end up becoming her superpower.');
INSERT INTO quotes (quote) VALUES ('Spending time at national parks can be an exciting adventure, but this wasnt the type of excitement she was hoping to experience. As she contemplated the situation she found herself in, she knew shed gotten herself in a little more than she bargained for.');
INSERT INTO quotes (quote) VALUES ('She was infatuated with color. She didnt have a favorite color per se, but she did have a fondness for teals and sea greens. You could see it in the clothes she wore that color was an important part of her overall style.');
INSERT INTO quotes (quote) VALUES ('She wondered if the note had reached him. She scolded herself for not handing it to him in person. She trusted her friend, but so much could happen. She waited impatiently for word.');
INSERT INTO quotes (quote) VALUES ('I inadvertently went to Sees Candy last week (I was in the mall looking for phone repair), and as it turns out, Sees Candy now charges a dollar for even the simplest of their wee confection offerings.');
INSERT INTO quotes (quote) VALUES ('It was just a burger. Why couldnt she understand that? She knew hed completely changed his life around her eating habits, so why couldnt she give him a break this one time? She wasnt even supposed to have found out.');
INSERT INTO quotes (quote) VALUES ('His mother had always taught him not to ever think of himself as better than others. Hed tried to live by this motto. He never looked down on those who were less fortunate or who had less money than him.');
INSERT INTO quotes (quote) VALUES ('Indescribable oppression, which seemed to generate in some unfamiliar part of her consciousness, filled her whole being with a vague anguish. It was like a shadow, like a mist passing across her souls summer day.');
INSERT INTO quotes (quote) VALUES ('Matt told her to reach for the stars, but Veronica thought it was the most ridiculous advice shed ever received. Sure, it had been well-meaning when he said it, but she didnt understand why anyone would want to suggest something that would literally kill you if you actually managed to achieve it.');
INSERT INTO quotes (quote) VALUES ('She sat in the darkened room waiting. It was now a standoff. He had the power to put her in the room, but not the power to make her repent. It wasnt fair and no matter how long she had to endure the darkness, she wouldnt change her attitude.');
-- INSERT INTO quotes (quote) VALUES ('');
-- INSERT INTO quotes (quote) VALUES ('');
-- INSERT INTO quotes (quote) VALUES ('');
-- INSERT INTO quotes (quote) VALUES ('');
-- INSERT INTO quotes (quote) VALUES ('');
-- INSERT INTO quotes (quote) VALUES ('');
-- INSERT INTO quotes (quote) VALUES ('');
-- INSERT INTO quotes (quote) VALUES ('');
-- INSERT INTO quotes (quote) VALUES ('');
-- INSERT INTO quotes (quote) VALUES ('');
-- INSERT INTO quotes (quote) VALUES ('');
-- INSERT INTO quotes (quote) VALUES ('');
-- INSERT INTO quotes (quote) VALUES ('');
-- INSERT INTO quotes (quote) VALUES ('');
-- INSERT INTO quotes (quote) VALUES ('');
-- INSERT INTO quotes (quote) VALUES ('');
-- INSERT INTO quotes (quote) VALUES ('');
-- INSERT INTO quotes (quote) VALUES ('');
-- INSERT INTO quotes (quote) VALUES ('');
-- INSERT INTO quotes (quote) VALUES ('');
-- INSERT INTO quotes (quote) VALUES ('');
-- INSERT INTO quotes (quote) VALUES ('');
-- INSERT INTO quotes (quote) VALUES ('');
-- INSERT INTO quotes (quote) VALUES ('');
-- INSERT INTO quotes (quote) VALUES ('');
-- INSERT INTO quotes (quote) VALUES ('');
-- INSERT INTO quotes (quote) VALUES ('');
-- INSERT INTO quotes (quote) VALUES ('');
-- INSERT INTO quotes (quote) VALUES ('');
-- INSERT INTO quotes (quote) VALUES ('');
-- INSERT INTO quotes (quote) VALUES ('');
-- INSERT INTO quotes (quote) VALUES ('');
-- INSERT INTO quotes (quote) VALUES ('');
-- INSERT INTO quotes (quote) VALUES ('');
-- INSERT INTO quotes (quote) VALUES ('');
-- INSERT INTO quotes (quote) VALUES ('');
-- INSERT INTO quotes (quote) VALUES ('');
-- INSERT INTO quotes (quote) VALUES ('');
-- INSERT INTO quotes (quote) VALUES ('');
-- INSERT INTO quotes (quote) VALUES ('');
-- INSERT INTO quotes (quote) VALUES ('');
-- INSERT INTO quotes (quote) VALUES ('');
-- INSERT INTO quotes (quote) VALUES ('');
-- INSERT INTO quotes (quote) VALUES ('');
-- INSERT INTO quotes (quote) VALUES ('');
-- INSERT INTO quotes (quote) VALUES ('');
-- INSERT INTO quotes (quote) VALUES ('');
-- INSERT INTO quotes (quote) VALUES ('');
-- INSERT INTO quotes (quote) VALUES ('');
-- INSERT INTO quotes (quote) VALUES ('');
-- INSERT INTO quotes (quote) VALUES ('');
-- INSERT INTO quotes (quote) VALUES ('');
-- INSERT INTO quotes (quote) VALUES ('');
-- INSERT INTO quotes (quote) VALUES ('');
-- INSERT INTO quotes (quote) VALUES ('');
-- INSERT INTO quotes (quote) VALUES ('');
-- INSERT INTO quotes (quote) VALUES ('');
-- INSERT INTO quotes (quote) VALUES ('');
-- INSERT INTO quotes (quote) VALUES ('');
-- INSERT INTO quotes (quote) VALUES ('');
-- INSERT INTO quotes (quote) VALUES ('');
-- INSERT INTO quotes (quote) VALUES ('');
-- INSERT INTO quotes (quote) VALUES ('');
-- INSERT INTO quotes (quote) VALUES ('');
-- INSERT INTO quotes (quote) VALUES ('');
-- INSERT INTO quotes (quote) VALUES ('');
-- INSERT INTO quotes (quote) VALUES ('');
-- INSERT INTO quotes (quote) VALUES ('');
-- INSERT INTO quotes (quote) VALUES ('');
-- INSERT INTO quotes (quote) VALUES ('');
-- INSERT INTO quotes (quote) VALUES ('');
-- INSERT INTO quotes (quote) VALUES ('');
-- INSERT INTO quotes (quote) VALUES ('');
-- INSERT INTO quotes (quote) VALUES ('');
-- INSERT INTO quotes (quote) VALUES ('');
-- INSERT INTO quotes (quote) VALUES ('');
-- INSERT INTO quotes (quote) VALUES ('');